### ISSUE TITLE
GitHub check fail in cmake_format/parser.py

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-tool#53]
GitHub check fail in cmake_format/parser.py in my branch, see https://github.com/axel-h/camkes-tool/runs/1806970220?check_suite_focus=true
I can't relly make sense of this error. Seem the format checker tool is broken here:
```
CRITICAL:root:[
'/home/runner/work/camkes-tool/camkes-tool/Findcamkes-tool.cmake',
'/home/runner/work/camkes-tool/camkes-tool/components/components.cmake',
'/home/runner/work/camkes-tool/camkes-tool/components/plat/pc99/plat/CMakeLists.txt',
'/home/runner/work/camkes-tool/camkes-tool/libsel4camkes/CMakeLists.txt',
'/home/runner/work/camkes-tool/camkes-tool/libcamkescakeml/CMakeLists.txt',
'/home/runner/work/camkes-tool/camkes-tool/camkes/templates/camkes-gen.cmake',
'/home/runner/work/camkes-tool/camkes-tool/camkes/templates/templates.cmake',
'/home/runner/work/camkes-tool/camkes-tool/camkes.cmake',
'/home/runner/work/camkes-tool/camkes-tool/camkes-top-level.cmake',
'/home/runner/work/camkes-tool/camkes-tool/CMakeLists.txt'
] failed with error code 1

While processing /home/runner/work/camkes-tool/camkes-tool/camkes/templates/camkes-gen.cmake
Traceback (most recent call last):
  File "/home/runner/.local/bin/cmake-format", line 8, in <module>
  sys.exit(main())
  File "/home/runner/.local/lib/python3.7/site-packages/cmake_format/__main__.py", line 421, in main
  process_file(cfg, infile, outfile, args.dump)
  File "/home/runner/.local/lib/python3.7/site-packages/cmake_format/__main__.py", line 110, in process_file
  parse_tree = parser.parse(tokens, config.fn_spec)
  File "/home/runner/.local/lib/python3.7/site-packages/cmake_format/parser.py", line 608, in parse
  return consume_body(tokens, cmdspec)
  File "/home/runner/.local/lib/python3.7/site-packages/cmake_format/parser.py", line 592, in consume_body
  tokens[0].begin.line, tokens[0].begin.col))
  AssertionError: Unexpected UNQUOTED_LITERAL token at 30:0
```

**Comment by axel-h** [comment]
seems this is basically #42
